FROM node:10-alpine AS alpine
WORKDIR /app
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package.json .
## install only the packages defined in the package-lock.json (faster than the normal npm install)
RUN npm install
# Copy the contents of the project to the image
COPY . .
# environement variable 
ENV REACT_APP_URL=http://127.0.0.1:4000
# Run 'npm start' when the container starts.
CMD ["npm", "run", "start"]
