FROM node:12.13.0-alpine AS alpine
WORKDIR /app
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package.json yarn.lock ./
## install only the packages defined in the yarn.lock(faster than the normal npm install)
RUN yarn
# Copy the contents of the project to the image
COPY . .
# Run 'npm start' when the container starts.
CMD ["npm", "run", "start"]
