apiVersion: v1
kind: Deployment
metadata:
  name: 8200-react-app
build:
  artifacts:
    - image: 8200-react-app
      sync:
        infer:
          - '**/*.ts'
          - '**/*.tsx'
          - '**/*.css'
          - '**/*.js'
      docker:
        dockerfile: Dockerfile.prod
deploy:
  kubectl:
    manifests:
      - deployment.yaml
portForward:
  - resourceType: deployment
    resourceName: create-react-app
    port: 3003
