version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
    volumes:
      - ./init/todo_db.sql:/docker-entrypoint-initdb.d/todo_db.sql
    ports:
      - '5432:5432'
  web-app:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    restart: on-failure
    container_name: web-app
    ports:
      - '80:80'
  todo-api:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    restart: on-failure
    container_name: todo-api
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
      - ./server:/app # Look at the server directory and copy everything into the app folder in the container
    environment:
      - PORT=4000
      - HOST=0.0.0.0
      - PGUSER=postgres
      - PGDATABASE=todo
      - PGPASSWORD=postgres
      - PGHOST=postgres
      - PGPORT=5432
