apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-todo-api
  labels:
    app: create-todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create-todo-api
  template:
    metadata:
      labels:
        app: create-todo-api
    spec:
      containers:
      - name: create-todo-api
        image: localhost:5000/to_do_8200ac-todo-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          value: postgres
        - name: PGHOST
          value: postgres-service
        - name: PGPORT
          value: '5432'
        - name: PGDATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: postgres-dbname
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: create-todo-api-service
spec:
  selector:
    app: create-todo-api
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 30000
